name: Generate index

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Generate Index
        run: |
            chmod +x indexer.py
            ./indexer.py
      - name: Commit and Push Changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add index.html all.html feed.xml gophermap
          git commit -m "regenerate indexes" || true
          git add html/*
          git commit -m "regenerate html pages" || true
          git push
